// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Spawn
#pragma kernel Lifetime

// Globals
RWTexture2DArray<half2> _Chunks;
StructuredBuffer<int> _SliceMap;

struct Chunk {
    int2 coords;
    int ppu;
    int size;
};

// Splat specific
Texture2D _SplatTex;
groupshared float2x2 _splatMatrix;

struct SplatSpawnData {
    int chunkIndex;           // Which chunk this splat belongs to
    int startX;
    int startY;
    int endX;
    int endY;
    float4 uvRect;            // Packed UV rect in atlas
    float4 linTran;           // 2x2 transform matrix packed as float4
    uint id;
};

StructuredBuffer<SplatSpawnData> _splatsSpawns;

[numthreads(8,8,1)]
void Spawn(uint3 tid : SV_DispatchThreadID) {
    if (tid.x == 0 && tid.y == 0) {
        _splatMatrix = float2x2(_SplatTransform.x, _SplatTransform.y, _SplatTransform.z, _SplatTransform.w);
    }
    GroupMemoryBarrierWithGroupSync();

    // proceed
}

// z is the chunks' index. Assume that this is dispatched w/ enough threads for each layer.
[numthreads(8,8,1)]
void Lifetime(uint3 tid : SV_DispatchThreadID) {
    half2 color = _Chunks[tid];
    color.g > 0.0 ? color.g -= 0.01 : color = 0;
    _Chunks[tid] = color;
}